name: lrst_py39
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python
  - hdf5
  - htslib
  - swig
  - matplotlib
  - plotly=4.14
  - pytest

# conda env create --file=environment.yml
# conda activate lrst_py39
