name: longreadsum
channels:
  - conda-forge
  - bioconda
  - defaults
  - jannessp  # for pod5
dependencies:
  - python=3.9
  - numpy
  - hdf5
  - ont_vbz_hdf_plugin
  - htslib=1.20
  - swig
  - plotly
  - pytest
  - pod5
  - pyarrow
