name: longreadsum
channels:
  - defaults
  - anaconda
  - conda-forge
  - bioconda
  - jannessp  # for pod5
dependencies:
  - python
  - numpy
  - hdf5
  - ont_vbz_hdf_plugin
  - htslib=1.20
  - swig
  - plotly
  - pytest
  - pod5
  - pyarrow

# conda env create --file=environment.yml
# conda activate longreadsum
