name: longreadsum
channels:
  - conda-forge
  - jannessp  # for pod5
  - bioconda
  - defaults

dependencies:
  - python
  - numpy
  - ont_vbz_hdf_plugin
  - bioconda::htslib=1.20
  - swig
  - plotly
  - pytest
  - jannessp::pod5
  - pyarrow
