name: lrst_py36
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - hdf5
  - htslib
  - samtools
  - swig
  - matplotlib
  - plotly=4.14
  - pytest
  - pytest-dependency
  - pip
  - pip:
          - kaleido

# conda env create --file=environment.yml
# conda activate lrst_py36
