name: longreadsum
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python
  - hdf5
  - htslib
  - swig
  - plotly
  - pytest

# conda env create --file=environment.yml
# conda activate longreadsum
