name: lrst_py39
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python
  - conda-build
  - hdf5
  - htslib
  - samtools
  - swig
  - matplotlib
  - plotly=4.14
  - pytest
  - pytest-dependency
  - pip

# conda env create --file=environment.yml
# conda activate lrst_py36
