name: lrst_py39
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - hdf5
  - htslib
  - samtools
  - swig
  - matplotlib
  - plotly=4.14
  - pytest
  - pytest-dependency
  - pip
  - pip:
          - kaleido
