name: longreadsum
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python
  - hdf5
  - htslib
  - swig
  - plotly=4.14


# conda env create --file=environment.yml
# conda activate lrst_py39
