#!/bin/bash

# Add the library path to the LD_LIBRARY_PATH
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PREFIX}/lib

# Show all files in src/
echo "Files in lib/ with .py extension:"
ls -l "${PREFIX}"/lib/*.py

# Run the entry point.py file
python "${PREFIX}"/lib/entry_point.py "$@"
