#!/bin/bash

# Add the library path to the LD_LIBRARY_PATH
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PREFIX}/lib

# Show the current directory
echo "Current directory"
ls -l .

# Check if the PREFIX variable is set
echo "PREFIX is set to ${PREFIX}"

# Show all directories in PREFIX
echo "Directories in PREFIX"
ls -l "${PREFIX}"

# Show all files in src/
echo "Files in src/"
ls -l "${PREFIX}"/src

# Run the entry point.py file
python "${PREFIX}"/src/entry_point.py "$@"
