{% set version = "1.4.0" %}
# {% set revision = "b06670513616fd6342233c1c77e6d0bcf138b3bc" %}

package:
  name: longreadsum
  version: {{ version }}

source:
  path: ../
  # git_url: https://github.com/WGLab/LongReadSum.git
  # git_rev: {{ revision }}

channels:
  - conda-forge
  - jannessp  # for pod5
  - bioconda
  - defaults

build:
  number: 0
  skip: true  # [py2k]
  entry_points:
    - longreadsum = entry_point:main

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - python=3.9
    - swig
    - hdf5
    - htslib=1.20
    # - jannessp::pod5
    # - jannessp::lib-pod5
  run:
    - python=3.9
    - numpy
    - hdf5
    - ont_vbz_hdf_plugin
    - htslib=1.20
    - plotly
    - janessp::pod5
    - pyarrow
    # - janessp::lib-pod5

test:
    commands:
        - longreadsum --help
about:
  home: https://github.com/WGLab/LongReadSum
  license: MIT
  summary: 'Long read sequencing quality control tool'
  description: |
    A fast and flexible QC tool for long read sequencing data.
  dev_url: https://github.com/WGLab/LongReadSum
  doc_url: https://github.com/WGLab/LongReadSum#readme
