{% set version = "1.5.0" %}
{% set revision = "47f1310e02ee06f32b8e34417e207f245828a319" %}

package:
  name: longreadsum
  version: {{ version }}

source:
  git_url: https://github.com/WGLab/LongReadSum.git
  git_rev: {{ revision }}
  # path: ../

channels:
  - conda-forge
  - jannessp  # for pod5
  - bioconda
  - defaults

build:
  number: 0
  skip: true  # [py2k]
  entry_points:
    - longreadsum = entry_point:main

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - python=3.9
    - swig
    - htslib=1.20
    - ont_vbz_hdf_plugin  # Contains HDF5 as a dependency as well
    # - jannessp::pod5
    # - jannessp::lib-pod5
  run:
    - python=3.9
    - numpy
    - ont_vbz_hdf_plugin
    - bioconda::htslib=1.20
    - plotly
    - jannessp::pod5
    - pyarrow
    # - janessp::lib-pod5

test:
    commands:
        - longreadsum --help
about:
  home: https://github.com/WGLab/LongReadSum
  license: MIT
  summary: 'Long read sequencing quality control tool'
  description: |
    A fast and flexible QC tool for long read sequencing data.
  dev_url: https://github.com/WGLab/LongReadSum
  doc_url: https://github.com/WGLab/LongReadSum#readme
