{% set version = "1.0.2.beta" %}

package:
  name: longreadsum
  version: {{ version }}

source:
  path: ..
#  git_url: https://github.com/WGLab/LongReadSum.git
#  git_rev: 4a9465d3e8ed585837d43347234b8682e53730ce
#  path: ..
#  git_url: https://github.com/WGLab/LongReadSum.git
#  git_rev: f16b80c5b74d6dc789668ed7b6d97cbab2082e44
#  git-tag: test-bioconda
#  sha256: 44406202ce8d529e5e126cd257517f0cab03ba0e
#  git_tag: v{{ version }}


build:
  number: 0

requirements:
  build:
    - python
    - make
    - {{ compiler('cxx') }}
    - swig
    - setuptools
    - hdf5
    - htslib>=1.9
  host:
    - python
    - hdf5
    - htslib>=1.9
  run:
    - python
    - hdf5
    - htslib>=1.9
    - matplotlib
    - plotly=4.14

test:
    commands:
        - longreadsum --help
about:
  home: https://github.com/WGLab/LongReadSum
  license: MIT
  summary: 'Long read sequencing data quality control tool'
  description: |
    A fast and flexible QC tool for long read sequencing data.
  dev_url: https://github.com/WGLab/LongReadSum
  doc_url: https://github.com/WGLab/LongReadSum#readme
#  doc_url: https://pypi.python.org/pypi/imagesize
#  doc_source_url: https://github.com/shibukawa/imagesize_py/blob/master/README.rst
# hdf5=1.12
# samtools=1.9
#    - htslib=1.6
