{% set version = "1.0.2.beta" %}

package:
  name: longreadsum
  version: {{ version }}

source:
  git_url: https://github.com/WGLab/LongReadSum.git
  git_rev: 8197fee3e967661a9247fb4951ba486525922436


build:
  number: 0

requirements:
  build:
    - python
    - make
    - {{ compiler('cxx') }}
    - swig
    - setuptools
    - hdf5
    - htslib>=1.9
  host:
    - python
    - hdf5
    - htslib>=1.9
  run:
    - python
    - hdf5
    - htslib>=1.9
    - matplotlib
    - plotly=4.14

test:
    commands:
        - longreadsum --help
about:
  home: https://github.com/WGLab/LongReadSum
  license: MIT
  summary: 'Long read sequencing data quality control tool'
  description: |
    A fast and flexible QC tool for long read sequencing data.
  dev_url: https://github.com/WGLab/LongReadSum
  doc_url: https://github.com/WGLab/LongReadSum#readme
