{% set version = "1.4.0" %}
{% set revision = "13ceda62f64fb78a6852ae7216aec30851c05fe5" %}

package:
  name: longreadsum
  version: {{ version }}

source:
  git_url: https://github.com/WGLab/LongReadSum.git
  git_rev: {{ revision }}

channels:
  - conda-forge
  - bioconda
  - defaults
  - jannessp  # for pod5

build:
  number: 0
  skip: true  # [py2k]
  entry_points:
    - longreadsum = entry_point:main

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - python=3.9
    - swig
    - hdf5
    - htslib=1.20
  run:
    - python=3.9
    - numpy
    - hdf5
    - ont_vbz_hdf_plugin
    - htslib=1.20
    - plotly
    - pod5
    - pyarrow

test:
    commands:
        - longreadsum --help
about:
  home: https://github.com/WGLab/LongReadSum
  license: MIT
  summary: 'Long read sequencing quality control tool'
  description: |
    A fast and flexible QC tool for long read sequencing data.
  dev_url: https://github.com/WGLab/LongReadSum
  doc_url: https://github.com/WGLab/LongReadSum#readme
