{% set version = "1.0.2.beta" %}

package:
  name: longreadsum
  version: {{ version }}

source:
  git_url: https://github.com/WGLab/LongReadSum.git
  git_rev: 5bb3be15bfe385484f2947b1126a5c3753dad9e8
#  git-tag: test-bioconda
#  sha256: 44406202ce8d529e5e126cd257517f0cab03ba0e
#  git_tag: v{{ version }}


build:
  number: 0

requirements:
  build:
    - python >=3.7
    - make
    - {{ compiler('cxx') }}
    - swig
    - setuptools >=38.6.0
    - htslib
    - hdf5=1.12.1
  host:
    - python
  run:
    - python
    - htslib
    - hdf5=1.12.1
    - matplotlib
    - plotly=4.14

test:
    commands:
        - longreadsum --help
about:
  home: https://github.com/WGLab/LongReadSum
  license: MIT
  summary: 'Long read sequencing data quality control tool'
  description: |
    A fast and flexible QC tool for long read sequencing data.
  dev_url: https://github.com/WGLab/LongReadSum
  doc_url: https://github.com/WGLab/LongReadSum#readme
#  doc_url: https://pypi.python.org/pypi/imagesize
#  doc_source_url: https://github.com/shibukawa/imagesize_py/blob/master/README.rst
