{% set version = "1.3.1" %}
{% set revision = "725c239b6c1f4d6daf5788871cd47f8781358e3d" %}

package:
  name: longreadsum
  version: {{ version }}

source:
  git_url: https://github.com/WGLab/LongReadSum.git
  git_rev: {{ revision }}

build:
  number: 0
  skip: true  # [py2k]
  entry_points:
    - longreadsum = entry_point:main

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - swig
    - hdf5
    - htslib
  run:
    - python
    - numpy
    - hdf5
    - htslib
    - plotly

test:
    commands:
        - longreadsum --help
about:
  home: https://github.com/WGLab/LongReadSum
  license: MIT
  summary: 'Long read sequencing quality control tool'
  description: |
    A fast and flexible QC tool for long read sequencing data.
  dev_url: https://github.com/WGLab/LongReadSum
  doc_url: https://github.com/WGLab/LongReadSum#readme
