# This workflow will build and test LongReadSum

name: build tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download assets
      uses: dsaltares/fetch-gh-release-asset@1.0.0
      with:
        repo: 'WGLab/LongReadSum'
        version: 'tags/v1.3.1'
        file: 'SampleData.zip'

    - name: Unzip assets
      shell: bash --login {0}
      run: unzip SampleData.zip

    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: longreadsum
        environment-file: environment.yml
        python-version: 3.9
        auto-activate-base: false

    - name: Check conda environment activation
      shell: bash --login {0}
      run: |
        conda info --envs
        which python
        python --version
        conda list | grep htslib
        conda list | grep hdf5

    - name: Build LongReadSum
      shell: bash --login {0}  # --login enables PATH variable access
      run: |
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/share/miniconda/envs/longreadsum/lib
        conda info --envs
        which python
        python --version
        conda list | grep htslib
        conda list | grep hdf5
        ls /usr/share/miniconda/envs/longreadsum/lib | grep hts
        ls /usr/share/miniconda/envs/longreadsum/lib | grep hdf5
        make

    - name: Run tests
      shell: bash --login {0}
      run: |
        mkdir output  # Unit test output folder
        python -m pytest
