# This workflow will build LongReadSum

name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: lrst_py39
        environment-file: environment.yml
        python-version: 3.9
        auto-activate-base: false
    - name: make
      shell: bash --login {0}  # --login enables PATH variable access
      run: make
