# This workflow will build LongReadSum

name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: lrst_py39
        environment-file: environment.yml
        python-version: 3.9
        auto-activate-base: false
    - name: Build LongReadSum
      shell: bash --login {0}  # --login enables PATH variable access
      run: make
    - name: Download assets
      uses: dsaltares/fetch-gh-release-asset@1.0.0
      with:
        repo: 'WGLab/LongReadSum'
        version: 'tags/v0.1.0'
        file: 'FASTA.zip'
        target: 'TestInputs/FASTA.zip'
    - name: Run tests
      shell: bash --login {0}
      run: |
        pip install pytest
        pip install pytest-cov
        pytest test/test_statistics.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
